version: "3"
services:

  server:
    build:
      context: ./
      dockerfile: cmd/server/Dockerfile
    ports:
      - "8080:8080/udp"
    networks:
      - public

  proxy:
    build:
      context: ./
      dockerfile: cmd/proxy/Dockerfile
    ports:
      - "1080:1080/tcp"
    networks:
      - public
      - private

  client:
    build:
      context: ./
      dockerfile: cmd/client/Dockerfile
    expose:
      - "8081/udp"
    networks:
      - private

networks:
  public:
    driver: bridge
  private:
    driver: bridge
